#!/bin/bash -e

# ImgOptimize
#
# Copyright (c) 2021 Eduardo Klosowski
# License: MIT (see LICENSE for details)
#


optimize_gif() {
    if which gifsicle > /dev/null; then
        temp_file="$(mktemp --suffix=.gif)"
        if ! gifsicle -O3 -o "$temp_file" "$1"; then
            echo "Compression failed of $1"
            rm "$temp_file"
            return 1
        fi
        old_size="$(du -b "$1" | cut -f1)"
        new_size="$(du -b "$temp_file" | cut -f1)"
        if [ "$new_size" -lt "$old_size" ]; then
            echo "$1 optimized in $((old_size - new_size)) bytes"
            cat "$temp_file" > "$1"
        else
            echo "$1 already optimized"
        fi
        rm "$temp_file"
    else
        echo "gifsicle not found"
        return 1
    fi
}


optimize_jpg() {
    if which jpegoptim > /dev/null; then
        jpegoptim -s "$1"
    elif which jpegtran > /dev/null; then
        temp_file="$(mktemp --suffix=.jpg)"
        if ! jpegtran -copy none -progressive -outfile "$temp_file" "$1"; then
            echo "Compression failed of $1"
            rm "$temp_file"
            return 1
        fi
        old_size=$(du -b "$1" | cut -f1)
        new_size=$(du -b "$temp_file" | cut -f1)
        if [ "$new_size" -lt "$old_size" ]; then
            echo "$1 optimized in $((old_size - new_size)) bytes"
            cat "$temp_file" > "$1"
        else
            echo "$1 already optimized"
        fi
        rm "$temp_file"
    else
        echo "jpegoptim or jpegtran not found"
        return 1
    fi
}


optimize_png() {
    if which optipng > /dev/null; then
        if ! optipng -preserve "$1"; then
            echo "Compression failed of $1"
            return 1
        fi
    else
        echo "optipng not found"
        return 1
    fi
}


main() {
    exitstatus=0
    for filename in "$@"; do
        if [ -e "$filename" ]; then
            filetype="$(file "$filename" | sed -r 's/^.{'${#filename}'}: ([^ ]+).*/\1/')"
            case "$filetype" in
                GIF)
                    if ! optimize_gif "$filename"; then
                        exitstatus=1
                    fi
                    ;;
                JPEG)
                    if ! optimize_jpg "$filename"; then
                        exitstatus=1
                    fi
                    ;;
                PNG)
                    if ! optimize_png "$filename"; then
                        exitstatus=1
                    fi
                    ;;
                *)
                    echo "$filetype of $filename is not supported"
                    exitstatus=2
                    ;;
            esac
        else
            echo "File $filename not found"
            exitstatus=2
        fi
    done
    exit $exitstatus
}


main "$@"
